### ISSUE TITLE
Spec has a binary field - openapi-first failing with exception trying to get the :tempfile

### ISSUE THREAD

**Issue by neongrau** [ahx/openapi_first#240]
Field isn't in required so by default it is optional. Yet it's tried to be read.

`data` is the payload, `property` the name (image in my case) but it wasn't sent so `data['image'] # nil`

```ruby
    def binary_format(data, property, property_schema, _parent)
      return unless property_schema.is_a?(Hash) && property_schema['format'] == 'binary'

      data[property] = data[property][:tempfile].read ### 
    end
```

**Comment by ahx** [comment]
@neongrau can you share (parts of) your API description to build a realistic test case?

**Comment by ahx** [comment]
Hi @neongrau I have added a fix in https://github.com/ahx/openapi_first/pull/241 ([branch](https://github.com/ahx/openapi_first/tree/fix-optional-file-upload)). Can you test this?

There are quite a few ways to describe file-uploads in OpenAPI, but I have not worked with any of them really. So I would like to know how people would like to use this feature.

**Comment by neongrau** [comment]
> Hi @neongrau I have added a fix in #241 ([branch](https://github.com/ahx/openapi_first/tree/fix-optional-file-upload)). Can you test this?
> 
> There are quite a few ways to describe file-uploads in OpenAPI, but I have not worked with any of them really. So I would like to know how people would like to use this feature.

Hi and thanks for the fast reply!

Mostly my endpoints are used with just JSON:API data. For files, some smaller ones can be supplied as Base64 encoded. Though some endpoints would handle documents (PDF handbooks) that can be quite large and these are very memory intense to handle as Base64. So i ended with openapi specs that handle json as well as multipart-form-data.

```yaml
                data[image]:
                  type: string
                  format: binary
                  writeOnly: true
                  description: multipart form data image to upload
                data[image_data_uri]:
                  type: string
                  writeOnly: true
                  description: base64 encoded image to upload
```

For real a full example see https://dev.samedis.care/api-docs/v4/public/index.html#?route=post-/api/v4/tenants/-tenant_id-/device_models/-device_model_id-/uploads

Will test you fix later today and give feedback.
