### ISSUE TITLE
Can't seem to get rid of a response validation error with format: byte, nullable true

### ISSUE THREAD

**Issue by neongrau** [ahx/openapi_first#250]
Field like this:
```yaml
        sign:
          type: string
          format: byte
          nullable: true
          description: data-URI of the employee signature
```
On records where there is not yet a value present
```json
      "links": {
        "sign": null
      }
```
Still getting 
```
value at `/data/0/links/sign` does not match format: byte
```

So i suspect the nullable attribute is getting ignored.

**Comment by ahx** [comment]
I just learned recently that using nullable  in OpenAPI 3.0 schemas does not disable other object constraints like "enum" or the like.  From the https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schemaNullable:
[…] A true value adds "null" to the allowed type specified by the type keyword, only if type is explicitly defined within the same Schema Object. Other Schema Object constraints retain their defined behavior, and therefore may disallow the use of null as a value. A false value leaves the specified or default type unmodified. The default value is false.
S for example { type: 'string', enum: ['a', 'b'], nullable: true  } does not allow null  as a value.

**Comment by MrBananaLord** [comment]
are you using 3.0 or 3.1? because in 3.1 you have new syntax (per migration guide https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0):
```
       sign:
          type: [string, "null"]
          format: byte
          nullable: true
          description: data-URI of the employee signature
```
