### ISSUE TITLE
Support "nullable" (OpenApi 3.0 only)

### ISSUE THREAD

**Issue by ahx** [ahx/openapi_first#32]
Currently OpenapiFirst does not support "nullable" of the OpenApi flavoured JSON Schema.

~~See https://github.com/davishmcclurg/json_schemer/issues/22~~

**Comment by ahx** [comment]
json_schemer is currently not a good place to impement something like that. 
Here's an idea for a new rubygem:

```ruby
require 'openapi-json-schema-converter'
OpenapiJsonSchemaConverter.new(openapi_json_schema).call(data) # => standard_json_schema
```

**Comment by tristandruyen** [comment]
@ahx 
FYI this is a workaround we found:
```yaml
some_thing:
  oneOf:
    - type: 'null'   # Note the quotes around 'null'
    - type: string
```

which could be improved once OpenAPI 3.1 (#46) is supported to:

```yaml
some_thing:
  type: ['null',string]
```

so does this even need to stay open?
