### ISSUE TITLE
Parameter objects included via `$ref`s break load for 3.0.x specs

### ISSUE THREAD

**Issue by clarkenciel** [ahx/openapi_first#348]
Reproduction [here](https://github.com/clarkenciel/openapifirst-load-bug)

`OpenapiFirst#load` throws an error on specs that include an [`OperationObject`](https://spec.openapis.org/oas/v3.0.3.html#operation-object) with a [`ReferenceObject`](https://spec.openapis.org/oas/v3.0.3.html#reference-object) as a parameter, e.g.:

```yaml
# spec/parameters.yaml
id:
  name: id
  in: path
  required: true
  schema:
    type: string
```

```yaml
# spec.yaml
paths:
  /test/{id}:
    get:
      operationId: test
      summary: example test
      parameters: 
        # this ref breaks load:
        - $ref: spec/parameters.yaml#/id
```

According to [the spec for `OperationObject`s](https://spec.openapis.org/oas/v3.0.3.html#operation-object) this should be valid and it works if the `openapi` version is set to `"3.1.0"`.
